#!/usr/bin/env bash
cd "$CLAUDE_PROJECT_DIR" || exit 0
file=$(jq -r '.tool_input.file_path // empty')

case "$file" in
  */internal/catalog/queries/*.sql|*/internal/catalog/migrations/*.sql)
    if ! out=$(go tool sqlc generate 2>&1); then
      echo "sqlc generate failed:" >&2; echo "$out" >&2; exit 2
    fi ;;
  */internal/catalog/db/*)
    echo "internal/catalog/db is generated by sqlc. Edit queries/*.sql and run make generate." >&2
    exit 2 ;;
  *.go)
    golangci-lint fmt "$file" >/dev/null 2>&1
    if ! out=$(golangci-lint run "$(dirname "$file")" 2>&1); then
      echo "golangci-lint errors in $(dirname "$file"):" >&2; echo "$out" >&2; exit 2
    fi ;;
  */agent/*.py)
    [ -f agent/pyproject.toml ] || exit 0 # until plan 2.0 creates the uv project
    (cd agent && uv run --frozen ruff format "$file" >/dev/null 2>&1)
    if ! out=$(cd agent && uv run --frozen ruff check "$file" 2>&1); then
      echo "ruff errors in $file:" >&2; echo "$out" >&2; exit 2
    fi ;;
esac
