// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"
	"database/sql"
)

const findSellerLink = `-- name: FindSellerLink :one
SELECT Id, SellerName, ProductId, SellerProductId FROM SellerProduct
WHERE SellerName = ? AND SellerProductId = ?
`

type FindSellerLinkParams struct {
	SellerName      string
	SellerProductID string
}

func (q *Queries) FindSellerLink(ctx context.Context, arg FindSellerLinkParams) (SellerProduct, error) {
	row := q.db.QueryRowContext(ctx, findSellerLink, arg.SellerName, arg.SellerProductID)
	var i SellerProduct
	err := row.Scan(
		&i.ID,
		&i.SellerName,
		&i.ProductID,
		&i.SellerProductID,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO Product (Name, Brand, Category) VALUES (?, ?, ?) RETURNING Id
`

type InsertProductParams struct {
	Name     string
	Brand    sql.NullString
	Category sql.NullString
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertProduct, arg.Name, arg.Brand, arg.Category)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSellerLink = `-- name: InsertSellerLink :one
INSERT INTO SellerProduct (SellerName, ProductId, SellerProductId) VALUES (?, ?, ?) RETURNING Id
`

type InsertSellerLinkParams struct {
	SellerName      string
	ProductID       int64
	SellerProductID string
}

func (q *Queries) InsertSellerLink(ctx context.Context, arg InsertSellerLinkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSellerLink, arg.SellerName, arg.ProductID, arg.SellerProductID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listProducts = `-- name: ListProducts :many
SELECT Id, Name, Brand, Category FROM Product ORDER BY Id
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
