// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Product struct {
	ID       int64
	Name     string
	Brand    sql.NullString
	Category sql.NullString
}

type SellerProduct struct {
	ID              int64
	SellerName      string
	ProductID       int64
	SellerProductID string
}
